name: 'Google Photos exporter'
description: 'Exports Google Photos to different targets'
inputs:
  googlePhotosClientId:
    description: 'Google photos client ID'
    required: true
  googlePhotosClientSecret:
    description: 'Google photos client secret'
    required: true
  googlePhotosRefreshToken:
    description: 'Google photos refresh token'
    required: true
  target:
    description: 'Where to store content (github or dropbox)'
    required: true
  githubAccessToken:
    description: 'GitHub access token'
    required: false
  githubRepositoryOwner:
    description: 'GitHub repository owner'
    required: false
  githubRepositoryName:
    description: 'GitHub repository name'
    required: false
  dropboxAppKey:
    description: 'Dropbox app key'
    required: false
  dropboxAppSecret:
    description: 'Dropbox app secret'
    required: false
  dropboxRefreshToken:
    description: 'Dropbox refresh token'
    required: false
  boxClientId:
    description: 'Box client ID'
    required: false
  boxClientSecret:
    description: 'Box client secret'
    required: false
  boxUserId:
    description: 'Box user ID'
    required: false
  itemType:
    description: 'Allows exporting just specific item types (photo or video)'
    required: false
  prefixPath:
    description: 'Path to be used as base for the exported files'
    required: false
  maxChunkSize:
    description: 'Maximum size (in MB) of each chunk'
    required: false
  offsetId:
    description: 'ID of the item to use as offset (not included)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.target }}
    - ${{ inputs.itemType }}
    - ${{ inputs.prefixPath }}
    - ${{ inputs.maxChunkSize }}
    - ${{ inputs.offsetId }}
  env:
    GOOGLE_PHOTOS_CLIENT_ID: ${{ inputs.googlePhotosClientId }}
    GOOGLE_PHOTOS_CLIENT_SECRET: ${{ inputs.googlePhotosClientSecret }}
    GOOGLE_PHOTOS_REFRESH_TOKEN: ${{ inputs.googlePhotosRefreshToken }}
    GITHUB_ACCESS_TOKEN: ${{ inputs.githubAccessToken }}
    GITHUB_REPOSITORY_OWNER: ${{ inputs.githubRepositoryOwner }}
    GITHUB_REPOSITORY_NAME: ${{ inputs.githubRepositoryName }}
    DROPBOX_APP_KEY: ${{ inputs.dropboxAppKey }}
    DROPBOX_APP_SECRET: ${{ inputs.dropboxAppSecret }}
    DROPBOX_REFRESH_TOKEN: ${{ inputs.dropboxRefreshToken }}
    BOX_CLIENT_ID: ${{ inputs.boxClientId }}
    BOX_CLIENT_SECRET: ${{ inputs.boxClientSecret }}
    BOX_USER_ID: ${{ inputs.boxUserId }}
branding:
  icon: 'camera'
  color: 'blue'