name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '19'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew shadowJar

      - name: Copy binary
        run: mkdir -p release && mv build/libs/google-photos-exporter.jar release

      - name: Commit binary
        uses: EndBug/add-and-commit@v9
        with:
          add: 'release/google-photos-exporter.jar'