name: export

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Google Photos exporter (photos)
        uses: patxibocos/google-photos-exporter@v1.0.0-beta
        with:
          target: github
          itemType: photo
          prefixPath: photos
          maxChunkSize: 50
          googlePhotosClientId: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          googlePhotosClientSecret: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          googlePhotosRefreshToken: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}
          githubAccessToken: ${{ secrets.GH_PHOTOS_REPOSITORY_TOKEN }}
          githubRepositoryOwner: ${{ secrets.GH_PHOTOS_REPOSITORY_OWNER }}
          githubRepositoryName: ${{ secrets.GH_PHOTOS_REPOSITORY_NAME }}

      - name: Google Photos exporter (videos)
        uses: patxibocos/google-photos-exporter@v1.0.0-beta
        with:
          target: github
          itemType: video
          prefixPath: videos
          maxChunkSize: 50
          googlePhotosClientId: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          googlePhotosClientSecret: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          googlePhotosRefreshToken: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}
          githubAccessToken: ${{ secrets.GH_VIDEOS_REPOSITORY_TOKEN }}
          githubRepositoryOwner: ${{ secrets.GH_VIDEOS_REPOSITORY_OWNER }}
          githubRepositoryName: ${{ secrets.GH_VIDEOS_REPOSITORY_NAME }}