name: export

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      exporter:
        type: choice
        default: github
        required: true
        description: Where to export to
        options:
          - github
          - dropbox
          - box

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Google Photos exporter (photos)
        uses: patxibocos/google-photos-exporter@v1.0.0-beta.2
        with:
          exporter: ${{ github.event.inputs.exporter }}
          itemType: photo
          prefixPath: photos
          maxChunkSize: 50
          googlePhotosClientId: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          googlePhotosClientSecret: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          googlePhotosRefreshToken: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}
          githubAccessToken: ${{ secrets.GH_PHOTOS_REPOSITORY_TOKEN }}
          githubRepositoryOwner: ${{ secrets.GH_PHOTOS_REPOSITORY_OWNER }}
          githubRepositoryName: ${{ secrets.GH_PHOTOS_REPOSITORY_NAME }}

      - name: Google Photos exporter (videos)
        uses: patxibocos/google-photos-exporter@v1.0.0-beta.2
        with:
          exporter: ${{ github.event.inputs.exporter }}
          itemType: video
          prefixPath: videos
          maxChunkSize: 50
          googlePhotosClientId: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          googlePhotosClientSecret: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          googlePhotosRefreshToken: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}
          githubAccessToken: ${{ secrets.GH_VIDEOS_REPOSITORY_TOKEN }}
          githubRepositoryOwner: ${{ secrets.GH_VIDEOS_REPOSITORY_OWNER }}
          githubRepositoryName: ${{ secrets.GH_VIDEOS_REPOSITORY_NAME }}
