name: export

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew shadowJar

      - name: Run photos exporter
        run: java -jar build/libs/google-photos-github-exporter.jar github -ro patxibocos -rn my-photos -it photo -pp photos
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_PHOTOS_REPOSITORY_TOKEN }}
          GOOGLE_PHOTOS_CLIENT_ID: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          GOOGLE_PHOTOS_CLIENT_SECRET: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          GOOGLE_PHOTOS_REFRESH_TOKEN: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}

      - name: Run videos exporter
        run: java -jar build/libs/google-photos-github-exporter.jar github -ro patxibocos -rn my-videos -it video -mcs 50 -pp videos
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_VIDEOS_REPOSITORY_TOKEN }}
          GOOGLE_PHOTOS_CLIENT_ID: ${{ secrets.GOOGLE_PHOTOS_CLIENT_ID }}
          GOOGLE_PHOTOS_CLIENT_SECRET: ${{ secrets.GOOGLE_PHOTOS_CLIENT_SECRET }}
          GOOGLE_PHOTOS_REFRESH_TOKEN: ${{ secrets.GOOGLE_PHOTOS_REFRESH_TOKEN }}